#!/bin/sh

out=./lib/jute.js
rm -f $out

echo "// Autogenerated file, don't change by hand" >> $out
echo "// Run build.sh from jute.js root to rebuild this file\n" >> $out

echo "(function () {" >> $out

cat ./src/utils.coffee | coffee -c -s -b >> $out
cat ./src/grammar.pegjs | `npm bin`/pegjs -O speed -e "parser" --format "globals" >> $out
cat ./src/expression.coffee | coffee -c -s -b >> $out
cat ./src/directives.coffee | coffee -c -s -b >> $out
cat ./src/jute.coffee | coffee -c -s -b >> $out

echo "}).call(this);" >> $out
