// Generated by CoffeeScript 1.10.0
(function() {
  var evalNode, transform;

  evalNode = function(node, scope) {
    var key, result, value;
    if (typeof node === 'object' && node !== null) {
      if (Array.isArray(node)) {
        return node.map(function(element) {
          return evalNode(element, scope);
        });
      } else {
        result = {};
        for (key in node) {
          value = node[key];
          result[key] = evalNode(value, scope);
        }
        return result;
      }
    } else {
      return node;
    }
  };

  transform = function(scope, template) {
    return evalNode(template, scope);
  };

  module.exports = {
    transform: transform
  };

}).call(this);
